# .cargo/config.toml

# This section applies to all builds unless overridden
[build]
# You can set general RUSTFLAGS here, but it's often better to use target-specific ones.

# Target-specific RUSTFLAGS for x86_64 architecture
# This will apply the flags when building for any x86_64 target.
# You can be more specific like `x86_64-unknown-linux-gnu` if needed.
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=skylake"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-cpu=skylake"]

#[target.x86_64-apple-darwin]
#rustflags = ["-C", "target-cpu=skylake"]

# You can add similar sections for other architectures if needed
# [target.aarch64-unknown-linux-gnu]
# rustflags = ["-C", "target-cpu=cortex-a72"] # Example for ARM